training:
  epochs: 30
  save_frequency: 1
  learning_rate: 0.08

data:
  sequence_length: 72     # = 6 hours
  time_of_day: True
  time_of_week: False
  time_of_year: True
  last_day_y: True
  two_last_day_y: True

model:
  lstm_depth: 2
  hidden_layers: 10
  dropout: 0.2
