# YAML-file copying example config given in assignment PDF
loss: cross_entropy
lrate: 0.01
wrt: None
wreg: 0.001
epochs: 10
debug: true

layers:
  - input: 100
  - size: 5
    act: sigmoid
    wr: glorot
  - softmax: false

dataset:
  dimension: 10
  number: 100
  flatten: true
  distribution: [70, 20, 10]
  noise: 0.00
  centering: 1.0