# YAML-file copying example config given in assignment PDF
loss: cross_entropy
lrate: 0.01
wrt: L2
wreg: 0.001
epochs: 50
debug: true

layers:
  - input: 225
  - size: 5
    act: sigmoid
    wr: glorot
  - softmax: true

dataset:
  dimension: 15
  number: 100
  flatten: true
  distribution: [70, 20, 10]
  noise: 0.00
  centering: 1.0