# YAML-file copying example config given in assignment PDF
loss: cross_entropy
lrate: 0.1
wrt: L2
wreg: 0.001
debug: true

layers:
  - input: 400
  - size: 100
    act: sigmoid
    wr: [-0.1, 0.1]
    lrate: 0.01
    br: [0, 1]
  - size: 50
    act: tanh
    wr: glorot
  - size: 25
    act: relu
    wr: [-0.5, 0.5]
  - size: 5
    act: linear
    wr: glorot
  - softmax: true

dataset:
  dimension: 20
  number: 500
  flatten: true
  distribution: [70, 20, 10]
  noise: 0.01
  centering: 0.0 